// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AuthForm: typeof import('./src/widgets/forms/AuthForm.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    FooterComponent: typeof import('./src/app/layout/FooterComponent.vue')['default']
    HeaderComponent: typeof import('./src/app/layout/HeaderComponent.vue')['default']
    RegistForm: typeof import('./src/widgets/forms/RegistForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VacanciesMap: typeof import('./src/widgets/VacanciesMap.vue')['default']
    VacanciesPanel: typeof import('./src/widgets/VacanciesPanel.vue')['default']
    VacancyBalloon: typeof import('./src/entities/vacancy/ui/vacancy-balloon.vue')['default']
    VacancyCard: typeof import('./src/entities/vacancy/ui/vacancy-card.vue')['default']
    VacancyFilter: typeof import('./src/widgets/VacancyFilter.vue')['default']
    VacancyList: typeof import('./src/widgets/VacancyList.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
